name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft-Repair
      uses: actions/checkout@v2
      with:
        path: Movecraft-Repair
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Movecraft-Repair
    - name: Build Movecraft-Repair
      run: mvn -B package -T 1C --file Movecraft-Repair/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Stage jar
      run: mkdir staging && cp Movecraft-Repair/target/Movecraft-Repair.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Repair*.jar staging/Movecraft-Repair_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Movecraft-Repair_Dev-Build
        path: staging/Movecraft-Repair_*.jar
